//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youbiquitous.Minimo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppCommons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppCommons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youbiquitous.Minimo.Resources.AppCommons", typeof(AppCommons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ahead.
        /// </summary>
        public static string Text_Ahead {
            get {
                return ResourceManager.GetString("Text_Ahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Text_Days {
            get {
                return ResourceManager.GetString("Text_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        public static string Text_DoubleDash {
            get {
                return ResourceManager.GetString("Text_DoubleDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functionality not available.
        /// </summary>
        public static string Text_FunctionNotAvailable {
            get {
                return ResourceManager.GetString("Text_FunctionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (he/him).
        /// </summary>
        public static string Text_He {
            get {
                return ResourceManager.GetString("Text_He", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Text_NA {
            get {
                return ResourceManager.GetString("Text_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on behalf of.
        /// </summary>
        public static string Text_OnBehalfOf {
            get {
                return ResourceManager.GetString("Text_OnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out of.
        /// </summary>
        public static string Text_OutOf {
            get {
                return ResourceManager.GetString("Text_OutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production DB.
        /// </summary>
        public static string Text_ProductionDb {
            get {
                return ResourceManager.GetString("Text_ProductionDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (she/her).
        /// </summary>
        public static string Text_She {
            get {
                return ResourceManager.GetString("Text_She", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Text_Test {
            get {
                return ResourceManager.GetString("Text_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Text_Year {
            get {
                return ResourceManager.GetString("Text_Year", resourceCulture);
            }
        }
    }
}
