//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youbiquitous.Minimo.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youbiquitous.Minimo.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The account is locked.
        /// </summary>
        public static string Err_AccountLocked {
            get {
                return ResourceManager.GetString("Err_AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A value is needed here.
        /// </summary>
        public static string Err_CantBeEmpty {
            get {
                return ResourceManager.GetString("Err_CantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Event not found.
        /// </summary>
        public static string Err_EventNotFound {
            get {
                return ResourceManager.GetString("Err_EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You need to enter the correct old password and repeat new password twice.
        /// </summary>
        public static string Err_FillAllPasswordFields {
            get {
                return ResourceManager.GetString("Err_FillAllPasswordFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unexpected error.
        /// </summary>
        public static string Err_Generic {
            get {
                return ResourceManager.GetString("Err_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Image is too big for us.
        /// </summary>
        public static string Err_ImageTooBig {
            get {
                return ResourceManager.GetString("Err_ImageTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to save the photo.
        /// </summary>
        public static string Err_ImgUploadFailed {
            get {
                return ResourceManager.GetString("Err_ImgUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a We need to know exact user name and password.
        /// </summary>
        public static string Err_IncompleteCredentials {
            get {
                return ResourceManager.GetString("Err_IncompleteCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid credentials.
        /// </summary>
        public static string Err_InvalidCredentials {
            get {
                return ResourceManager.GetString("Err_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid password.
        /// </summary>
        public static string Err_InvalidPassword {
            get {
                return ResourceManager.GetString("Err_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The operation could not be completed successfully.
        /// </summary>
        public static string Err_OperationFailed {
            get {
                return ResourceManager.GetString("Err_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The page is not available.
        /// </summary>
        public static string Err_PageNotAvailable {
            get {
                return ResourceManager.GetString("Err_PageNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The operation can&apos;t be performed due to security policies..
        /// </summary>
        public static string Err_UnauthorizedOperation {
            get {
                return ResourceManager.GetString("Err_UnauthorizedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User not found.
        /// </summary>
        public static string Err_UserNotFound {
            get {
                return ResourceManager.GetString("Err_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter a valid email address.
        /// </summary>
        public static string Err_ValidEmailRequired {
            get {
                return ResourceManager.GetString("Err_ValidEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connecting....
        /// </summary>
        public static string Info_Connecting {
            get {
                return ResourceManager.GetString("Info_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connecting.
        /// </summary>
        public static string Info_Connecting1 {
            get {
                return ResourceManager.GetString("Info_Connecting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Taking longer than expected.
        /// </summary>
        public static string Info_ConnectionIsTakingLonger {
            get {
                return ResourceManager.GetString("Info_ConnectionIsTakingLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please contact Crionet support.
        /// </summary>
        public static string Info_ContactSystemAdmin {
            get {
                return ResourceManager.GetString("Info_ContactSystemAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All done!.
        /// </summary>
        public static string Info_Done {
            get {
                return ResourceManager.GetString("Info_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A confirmation email has been sent to your inbox.
        /// </summary>
        public static string Info_EmailSentToInbox {
            get {
                return ResourceManager.GetString("Info_EmailSentToInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It just failed!.
        /// </summary>
        public static string Info_Failed {
            get {
                return ResourceManager.GetString("Info_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password has been reset and will be effective on your next access.
        /// </summary>
        public static string Info_PasswordBeenReset {
            get {
                return ResourceManager.GetString("Info_PasswordBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Changes saved successfully.
        /// </summary>
        public static string Info_SavedChanges {
            get {
                return ResourceManager.GetString("Info_SavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure? User will be deleted..
        /// </summary>
        public static string Msg_DeleteConfirm {
            get {
                return ResourceManager.GetString("Msg_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You&apos;re going to delete all entries. Confirm?.
        /// </summary>
        public static string Question_DeleteEntries {
            get {
                return ResourceManager.GetString("Question_DeleteEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The operation completed successfully.
        /// </summary>
        public static string Success_OperationCompleted {
            get {
                return ResourceManager.GetString("Success_OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password has been changed and will be effective on your next access.
        /// </summary>
        public static string Success_PasswordChanged {
            get {
                return ResourceManager.GetString("Success_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Run into a network issue .
        /// </summary>
        public static string System_ConnectionError {
            get {
                return ResourceManager.GetString("System_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a N/A.
        /// </summary>
        public static string System_InfoNotAvailable {
            get {
                return ResourceManager.GetString("System_InfoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Not implemented yet.
        /// </summary>
        public static string System_NotImplementedYet {
            get {
                return ResourceManager.GetString("System_NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Not specified.
        /// </summary>
        public static string System_NotSpecified {
            get {
                return ResourceManager.GetString("System_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Oops!.
        /// </summary>
        public static string System_Oops {
            get {
                return ResourceManager.GetString("System_Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Working hard....
        /// </summary>
        public static string System_OperationInProgress {
            get {
                return ResourceManager.GetString("System_OperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It&apos;s not you, but something unexpectedlywent wrong!.
        /// </summary>
        public static string System_SomethingWentWrong {
            get {
                return ResourceManager.GetString("System_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Where would you go from here?.
        /// </summary>
        public static string System_WhereFromHere {
            get {
                return ResourceManager.GetString("System_WhereFromHere", resourceCulture);
            }
        }
    }
}
