//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youbiquitous.Minimo.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youbiquitous.Minimo.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Our favorite way to write ASP.NET Core 8 apps.
        /// </summary>
        public static string App_AdditionalDescription {
            get {
                return ResourceManager.GetString("App_AdditionalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About.
        /// </summary>
        public static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Account.
        /// </summary>
        public static string Label_Account {
            get {
                return ResourceManager.GetString("Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Azioni.
        /// </summary>
        public static string Label_Actions {
            get {
                return ResourceManager.GetString("Label_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Team.
        /// </summary>
        public static string Label_Company {
            get {
                return ResourceManager.GetString("Label_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Country.
        /// </summary>
        public static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Date.
        /// </summary>
        public static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Standard.
        /// </summary>
        public static string Label_Default {
            get {
                return ResourceManager.GetString("Label_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Notes.
        /// </summary>
        public static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Details.
        /// </summary>
        public static string Label_Details {
            get {
                return ResourceManager.GetString("Label_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Details.
        /// </summary>
        public static string Label_Details1 {
            get {
                return ResourceManager.GetString("Label_Details1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string Label_DisplayName {
            get {
                return ResourceManager.GetString("Label_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a First name.
        /// </summary>
        public static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a found.
        /// </summary>
        public static string Label_Found {
            get {
                return ResourceManager.GetString("Label_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Headshot.
        /// </summary>
        public static string Label_Headshot {
            get {
                return ResourceManager.GetString("Label_Headshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ID.
        /// </summary>
        public static string Label_Id {
            get {
                return ResourceManager.GetString("Label_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Individual account.
        /// </summary>
        public static string Label_Individual {
            get {
                return ResourceManager.GetString("Label_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Information.
        /// </summary>
        public static string Label_Information {
            get {
                return ResourceManager.GetString("Label_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language.
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Last name.
        /// </summary>
        public static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Last update.
        /// </summary>
        public static string Label_LastUpdate {
            get {
                return ResourceManager.GetString("Label_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Last update.
        /// </summary>
        public static string Label_LatestUpdate {
            get {
                return ResourceManager.GetString("Label_LatestUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The link is no longer valid.
        /// </summary>
        public static string Label_LinkExpired {
            get {
                return ResourceManager.GetString("Label_LinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Location.
        /// </summary>
        public static string Label_Location {
            get {
                return ResourceManager.GetString("Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Location.
        /// </summary>
        public static string Label_Location1 {
            get {
                return ResourceManager.GetString("Label_Location1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Locked.
        /// </summary>
        public static string Label_Locked {
            get {
                return ResourceManager.GetString("Label_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logo.
        /// </summary>
        public static string Label_Logo {
            get {
                return ResourceManager.GetString("Label_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string Label_Name1 {
            get {
                return ResourceManager.GetString("Label_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Need help?.
        /// </summary>
        public static string Label_NeedHelp {
            get {
                return ResourceManager.GetString("Label_NeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New password.
        /// </summary>
        public static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Notes.
        /// </summary>
        public static string Label_Notes {
            get {
                return ResourceManager.GetString("Label_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Not specified.
        /// </summary>
        public static string Label_NotSpecified {
            get {
                return ResourceManager.GetString("Label_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Old password.
        /// </summary>
        public static string Label_OldPassword {
            get {
                return ResourceManager.GetString("Label_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (Optional) Notes.
        /// </summary>
        public static string Label_OptionalDescription {
            get {
                return ResourceManager.GetString("Label_OptionalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Organization.
        /// </summary>
        public static string Label_Organization {
            get {
                return ResourceManager.GetString("Label_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password reset.
        /// </summary>
        public static string Label_PasswordReset {
            get {
                return ResourceManager.GetString("Label_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password reset.
        /// </summary>
        public static string Label_PasswordReset1 {
            get {
                return ResourceManager.GetString("Label_PasswordReset1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Permissions.
        /// </summary>
        public static string Label_Permissions {
            get {
                return ResourceManager.GetString("Label_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Personal.
        /// </summary>
        public static string Label_Personal {
            get {
                return ResourceManager.GetString("Label_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Phone.
        /// </summary>
        public static string Label_Phone {
            get {
                return ResourceManager.GetString("Label_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please choose.
        /// </summary>
        public static string Label_PleaseChoose {
            get {
                return ResourceManager.GetString("Label_PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preferisco non dirlo.
        /// </summary>
        public static string Label_PreferNotToSay {
            get {
                return ResourceManager.GetString("Label_PreferNotToSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile properties.
        /// </summary>
        public static string Label_ProfileProperties {
            get {
                return ResourceManager.GetString("Label_ProfileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ready.
        /// </summary>
        public static string Label_Ready {
            get {
                return ResourceManager.GetString("Label_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter the registration email.
        /// </summary>
        public static string Label_RecoverPassword {
            get {
                return ResourceManager.GetString("Label_RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recover password.
        /// </summary>
        public static string Label_RecoverPassword1 {
            get {
                return ResourceManager.GetString("Label_RecoverPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Related accounts.
        /// </summary>
        public static string Label_RelatedAccounts {
            get {
                return ResourceManager.GetString("Label_RelatedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Repeat password.
        /// </summary>
        public static string Label_RepeatPassword {
            get {
                return ResourceManager.GetString("Label_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ruolo.
        /// </summary>
        public static string Label_Role {
            get {
                return ResourceManager.GetString("Label_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set new password.
        /// </summary>
        public static string Label_SetNewPassword {
            get {
                return ResourceManager.GetString("Label_SetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sign-in to continue.
        /// </summary>
        public static string Label_SigninToContinue {
            get {
                return ResourceManager.GetString("Label_SigninToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If correct, we&apos;ll email you the link to set a new password.
        /// </summary>
        public static string Label_TypeRegistrationEmail {
            get {
                return ResourceManager.GetString("Label_TypeRegistrationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User ID.
        /// </summary>
        public static string Label_UserId {
            get {
                return ResourceManager.GetString("Label_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome utente.
        /// </summary>
        public static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User properties.
        /// </summary>
        public static string Label_UserProperties {
            get {
                return ResourceManager.GetString("Label_UserProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Welcome.
        /// </summary>
        public static string Label_Welcome {
            get {
                return ResourceManager.GetString("Label_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Benvenuto.
        /// </summary>
        public static string Label_Welcome1 {
            get {
                return ResourceManager.GetString("Label_Welcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Where you can go from here.
        /// </summary>
        public static string Label_WhereFromHere {
            get {
                return ResourceManager.GetString("Label_WhereFromHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter your new password.
        /// </summary>
        public static string Placeholder_ChangePassword {
            get {
                return ResourceManager.GetString("Placeholder_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Let us know where you wish to receive the link to reset your password.
        /// </summary>
        public static string Placeholder_EmailResetPassword {
            get {
                return ResourceManager.GetString("Placeholder_EmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type to filter list ....
        /// </summary>
        public static string Placeholder_FilterList {
            get {
                return ResourceManager.GetString("Placeholder_FilterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a More tournaments.
        /// </summary>
        public static string Placeholder_OtherTournaments {
            get {
                return ResourceManager.GetString("Placeholder_OtherTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password.
        /// </summary>
        public static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password.
        /// </summary>
        public static string Placeholder_Password1 {
            get {
                return ResourceManager.GetString("Placeholder_Password1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a She who searches, finds....
        /// </summary>
        public static string Placeholder_SearchFor {
            get {
                return ResourceManager.GetString("Placeholder_SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User name or email.
        /// </summary>
        public static string Placeholder_UserName {
            get {
                return ResourceManager.GetString("Placeholder_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User name.
        /// </summary>
        public static string Placeholder_UserName1 {
            get {
                return ResourceManager.GetString("Placeholder_UserName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a accounts.
        /// </summary>
        public static string Text_Accounts {
            get {
                return ResourceManager.GetString("Text_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Active.
        /// </summary>
        public static string Text_Active {
            get {
                return ResourceManager.GetString("Text_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Activities.
        /// </summary>
        public static string Text_Activities {
            get {
                return ResourceManager.GetString("Text_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add.
        /// </summary>
        public static string Text_Add {
            get {
                return ResourceManager.GetString("Text_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Additional Info.
        /// </summary>
        public static string Text_AdditionalInfo {
            get {
                return ResourceManager.GetString("Text_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add New.
        /// </summary>
        public static string Text_AddNew {
            get {
                return ResourceManager.GetString("Text_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Address Information.
        /// </summary>
        public static string Text_AddressInformation {
            get {
                return ResourceManager.GetString("Text_AddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ago.
        /// </summary>
        public static string Text_Ago {
            get {
                return ResourceManager.GetString("Text_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a fa.
        /// </summary>
        public static string Text_Ago1 {
            get {
                return ResourceManager.GetString("Text_Ago1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ago.
        /// </summary>
        public static string Text_Ago2 {
            get {
                return ResourceManager.GetString("Text_Ago2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a are you trying to &lt;b&gt;delete&lt;/b&gt; this.
        /// </summary>
        public static string Text_AreYouTryingToDeleteThis {
            get {
                return ResourceManager.GetString("Text_AreYouTryingToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Basic Information.
        /// </summary>
        public static string Text_BasicInformation {
            get {
                return ResourceManager.GetString("Text_BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a da.
        /// </summary>
        public static string Text_By {
            get {
                return ResourceManager.GetString("Text_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a by.
        /// </summary>
        public static string Text_By1 {
            get {
                return ResourceManager.GetString("Text_By1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Choose an option.
        /// </summary>
        public static string Text_ChooseAnOption {
            get {
                return ResourceManager.GetString("Text_ChooseAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a team.
        /// </summary>
        public static string Text_Company {
            get {
                return ResourceManager.GetString("Text_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a team.
        /// </summary>
        public static string Text_Company1 {
            get {
                return ResourceManager.GetString("Text_Company1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contact.
        /// </summary>
        public static string Text_Contact {
            get {
                return ResourceManager.GetString("Text_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contact Groups.
        /// </summary>
        public static string Text_ContactGroups {
            get {
                return ResourceManager.GetString("Text_ContactGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contacts.
        /// </summary>
        public static string Text_Contacts {
            get {
                return ResourceManager.GetString("Text_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contact us.
        /// </summary>
        public static string Text_ContactUs {
            get {
                return ResourceManager.GetString("Text_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Continue.
        /// </summary>
        public static string Text_Continue {
            get {
                return ResourceManager.GetString("Text_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create.
        /// </summary>
        public static string Text_Create {
            get {
                return ResourceManager.GetString("Text_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Credentials by status.
        /// </summary>
        public static string Text_CredentialsByStatus {
            get {
                return ResourceManager.GetString("Text_CredentialsByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current Run.
        /// </summary>
        public static string Text_CurrentRun {
            get {
                return ResourceManager.GetString("Text_CurrentRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dashboard.
        /// </summary>
        public static string Text_Dashboard {
            get {
                return ResourceManager.GetString("Text_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dashboard.
        /// </summary>
        public static string Text_Dashboard1 {
            get {
                return ResourceManager.GetString("Text_Dashboard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a giorno.
        /// </summary>
        public static string Text_Day {
            get {
                return ResourceManager.GetString("Text_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a day.
        /// </summary>
        public static string Text_Day1 {
            get {
                return ResourceManager.GetString("Text_Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a days.
        /// </summary>
        public static string Text_DayPlural {
            get {
                return ResourceManager.GetString("Text_DayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a giorni.
        /// </summary>
        public static string Text_DayPlural1 {
            get {
                return ResourceManager.GetString("Text_DayPlural1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a days.
        /// </summary>
        public static string Text_DayPlural2 {
            get {
                return ResourceManager.GetString("Text_DayPlural2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete.
        /// </summary>
        public static string Text_Delete {
            get {
                return ResourceManager.GetString("Text_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Deleted.
        /// </summary>
        public static string Text_Deleted {
            get {
                return ResourceManager.GetString("Text_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a developed by Crionet.
        /// </summary>
        public static string Text_DevelopedBy {
            get {
                return ResourceManager.GetString("Text_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a developed by Crionet.
        /// </summary>
        public static string Text_DevelopedBy1 {
            get {
                return ResourceManager.GetString("Text_DevelopedBy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Documentation.
        /// </summary>
        public static string Text_Documentation {
            get {
                return ResourceManager.GetString("Text_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit.
        /// </summary>
        public static string Text_Edit {
            get {
                return ResourceManager.GetString("Text_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Editions.
        /// </summary>
        public static string Text_Editions {
            get {
                return ResourceManager.GetString("Text_Editions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email Templates.
        /// </summary>
        public static string Text_EmailTemplates {
            get {
                return ResourceManager.GetString("Text_EmailTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Events.
        /// </summary>
        public static string Text_Events {
            get {
                return ResourceManager.GetString("Text_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logo is preferably a landscape image.
        /// </summary>
        public static string Text_LandscapeLogo {
            get {
                return ResourceManager.GetString("Text_LandscapeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Local or external URL.
        /// </summary>
        public static string Text_LocalOrExternalUrl {
            get {
                return ResourceManager.GetString("Text_LocalOrExternalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New.
        /// </summary>
        public static string Text_New {
            get {
                return ResourceManager.GetString("Text_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Photo.
        /// </summary>
        public static string Text_Photo {
            get {
                return ResourceManager.GetString("Text_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile.
        /// </summary>
        public static string Text_Profile {
            get {
                return ResourceManager.GetString("Text_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile.
        /// </summary>
        public static string Text_Profile1 {
            get {
                return ResourceManager.GetString("Text_Profile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Runs.
        /// </summary>
        public static string Text_Runs {
            get {
                return ResourceManager.GetString("Text_Runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cerca.
        /// </summary>
        public static string Text_Search {
            get {
                return ResourceManager.GetString("Text_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search.
        /// </summary>
        public static string Text_Search1 {
            get {
                return ResourceManager.GetString("Text_Search1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cerca per.
        /// </summary>
        public static string Text_SearchFor {
            get {
                return ResourceManager.GetString("Text_SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search for.
        /// </summary>
        public static string Text_SearchFor1 {
            get {
                return ResourceManager.GetString("Text_SearchFor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Identificati per accedere a.
        /// </summary>
        public static string Text_SigninToContinue {
            get {
                return ResourceManager.GetString("Text_SigninToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tenant.
        /// </summary>
        public static string Text_Tenant {
            get {
                return ResourceManager.GetString("Text_Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tenants.
        /// </summary>
        public static string Text_Tenants {
            get {
                return ResourceManager.GetString("Text_Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a today.
        /// </summary>
        public static string Text_Today {
            get {
                return ResourceManager.GetString("Text_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a oggi.
        /// </summary>
        public static string Text_Today1 {
            get {
                return ResourceManager.GetString("Text_Today1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a today.
        /// </summary>
        public static string Text_Today2 {
            get {
                return ResourceManager.GetString("Text_Today2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User.
        /// </summary>
        public static string Text_User {
            get {
                return ResourceManager.GetString("Text_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Users.
        /// </summary>
        public static string Text_Users {
            get {
                return ResourceManager.GetString("Text_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a View full list.
        /// </summary>
        public static string Text_ViewFullList {
            get {
                return ResourceManager.GetString("Text_ViewFullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Year.
        /// </summary>
        public static string Text_Year {
            get {
                return ResourceManager.GetString("Text_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a yesterday.
        /// </summary>
        public static string Text_Yesterday {
            get {
                return ResourceManager.GetString("Text_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a yesterday.
        /// </summary>
        public static string Text_Yesterday2 {
            get {
                return ResourceManager.GetString("Text_Yesterday2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Work.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
    }
}
